from plotstyle import *

parseval_train_acc = np.load("classifier_data/overfit/parseval_train_acc.npy")
parseval_val_acc = np.load("classifier_data/overfit/parseval_val_acc.npy")
parseval_steps = np.load("classifier_data/overfit/parseval_steps.npy")
vanilla_train_acc = np.load("classifier_data/overfit/vanilla_train_acc.npy")
vanilla_val_acc = np.load("classifier_data/overfit/vanilla_val_acc.npy")
vanilla_steps = np.load("classifier_data/overfit/vanilla_steps.npy")

plt.figure(figsize=[6, 4])
plt.plot(parseval_steps, parseval_train_acc)
plt.plot(parseval_steps, parseval_val_acc)
# plt.xlabel("Iterations")
plt.ylim([-5, 110])
plt.legend(["Training accuracy", "Validation accuracy"], loc=4)
plt.tight_layout()
plt.savefig("overfit_training_acc_parseval.pdf", facecolor='none')
# plt.show()

plt.figure(figsize=[6, 4])
plt.plot(vanilla_steps, vanilla_train_acc)
plt.plot(vanilla_steps, vanilla_val_acc)
# plt.xlabel("Iterations")
plt.ylim([-5, 110])
plt.legend(["Training accuracy", "Validation accuracy"], loc=4)
plt.tight_layout()
plt.savefig("overfit_training_acc_vanilla.pdf", facecolor='none')
# plt.show()


parseval_train_acc = np.load("classifier_data/fit/parseval_train_acc.npy")
parseval_val_acc = np.load("classifier_data/fit/parseval_val_acc.npy")
parseval_steps = np.load("classifier_data/fit/parseval_steps.npy")
vanilla_train_acc = np.load("classifier_data/fit/vanilla_train_acc.npy")
vanilla_val_acc = np.load("classifier_data/fit/vanilla_val_acc.npy")
vanilla_steps = np.load("classifier_data/fit/vanilla_steps.npy")

plt.figure(figsize=[6, 4])
plt.plot(parseval_steps, parseval_train_acc)
plt.plot(parseval_steps, parseval_val_acc)
# plt.xlabel("Iterations")
plt.ylim([-5, 110])
plt.legend(["Training accuracy", "Validation accuracy"], loc=4)
plt.tight_layout()
plt.savefig("fit_training_acc_parseval.pdf", facecolor='none')
# plt.show()

plt.figure(figsize=[6, 4])
plt.plot(vanilla_steps, vanilla_train_acc)
plt.plot(vanilla_steps, vanilla_val_acc)
# plt.xlabel("Iterations")
plt.ylim([-5, 110])
plt.legend(["Training accuracy", "Validation accuracy"], loc=4)
plt.tight_layout()
plt.savefig("fit_training_acc_vanilla.pdf", facecolor='none')
# plt.show()